# Generated by Django 4.1 on 2024-05-06 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'рубрика',
                'verbose_name_plural': 'Рубрики',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='bd',
            options={'ordering': ['-published'], 'verbose_name': 'объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AddField(
            model_name='bd',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='board.rubric', verbose_name='Рубрика'),
        ),
    ]
